version: 0.1

phases:
  pre_build:
    commands:
      - terraform remote config -backend=s3 -backend-config="bucket=${TERRAFORM_STATE_BUCKET}" -backend-config="key=${REGION}/${PROJECT}/${ENVIRONMENT}/${MODULE}/terraform.tfstate" -backend-config="region=${TERRAFORM_STATE_BUCKET_REGION}"
      - terraform get
  build:
    commands:
      - terraform plan
